config/routes.rb
Rails.application.routes.draw do
  resources :programs
  resources :enrollments
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :teacher, foreign_key: :teacher_id, class_name: 'User'
  belongs_to :program
end

app/models/program.rb
class Program < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  TEACHER = "teacher"
  STUDENT = "student"
  
  enum :kind, [:student, :teacher, :teacher_student]
  
  has_many :enrollments
  has_many :programs, through: :enrollments
  has_many :teacher_enrollments, class_name: 'Enrollment', foreign_key: 'teacher_id'

  before_update :validate_enrollment_present?

  def teachers
    User.joins(:teacher_enrollments).where(id: teacher_ids, teacher_enrollments: { user_id: id }).distinct
  end

  def teacher_ids
    teacher_ids = enrollments.pluck(:teacher_id)
  end

  class << self
    def favorites
      where(teacher_enrollments: { favorite: true })
    end

    def classmates(user)
      User.joins(:enrollments).where(
        enrollments: { program: user.programs }
      ).where.not(
        enrollments: { user_id: user.id }
      ).distinct
    end
  end

  private

  def validate_enrollment_present?
    return true unless kind_changed?

    if kind_change[0] == TEACHER
      teacher_enrollments.exists? ? log_error(kind: kind, action: "teaching") : true
    elsif kind_change[0] == STUDENT
      enrollments.exists? ? log_error(kind: kind, action: "studying") : true
    else
      true
    end
  end

  def log_error(kind:, action:)
    errors.add(:kind, I18n.t("user.error.kind.message", kind: kind, action: action))
    throw(:abort)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :teacher_id)
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[ show edit update destroy ]

  # GET /programs or /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1 or /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs or /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to program_url(@program), notice: "Program was successfully created." }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1 or /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to program_url(@program), notice: "Program was successfully updated." }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1 or /programs/1.json
  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url, notice: "Program was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>User:</strong>
    <%= enrollment.user_id %>
  </p>

  <p>
    <strong>Teacher:</strong>
    <%= enrollment.teacher_id %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :teacher_id, style: "display: block" %>
    <%= form.number_field :teacher_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollments</h1>

<div id="enrollments">
  <% @enrollments.each do |enrollment| %>
    <%= render enrollment %>
    <p>
      <%= link_to "Show this enrollment", enrollment %>
    </p>
  <% end %>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewHires</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programs/_form.html.erb
<%= form_with(model: program) do |form| %>
  <% if program.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
        <% program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/programs/_program.html.erb
<div id="<%= dom_id program %>">
  <p>
    <strong>Name:</strong>
    <%= program.name %>
  </p>

</div>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render "form", program: @program %>

<br>

<div>
  <%= link_to "Show this program", @program %> |
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Programs</h1>

<div id="programs">
  <% @programs.each do |program| %>
    <%= render program %>
    <p>
      <%= link_to "Show this program", program %>
    </p>
  <% end %>
</div>

<%= link_to "New program", new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render "form", program: @program %>

<br>

<div>
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @program %>

<div>
  <%= link_to "Edit this program", edit_program_path(@program) %> |
  <%= link_to "Back to programs", programs_path %>

  <%= button_to "Destroy this program", @program, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.select :kind, User.kinds.keys.map{ |key| [key.humanize, key] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= user.kind %>
  </p>

  <p id='favorite_teachers'>
    <strong>Favorite Teachers:</strong>
    <%= user.teachers.favorites.ids.map {|user_id| User.find(user_id).name }.join(', ') %>
  </p>

  <p id='classmates'>
    <strong>Class Mates:</strong>
    <%= User.classmates(user).map(&:name).join(', ') %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>